spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pharm-palm-deploy.cuuqf4019hgl.ap-northeast-2.rds.amazonaws.com:13306/pharm_palm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_NAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${K_CLIENT_ID}
            redirect-uri: "http://pharm-palm-deploy.s3-website.ap-northeast-2.amazonaws.com/auth/kakao/callback"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email, gender, age_range
            client-name: Kakao
          naver:
            client-id: ${N_CLIENT_ID}
            client-secret: ${N_CLIENT_SECRET}
            redirect-uri: "http://pharm-palm-deploy.s3-website.ap-northeast-2.amazonaws.com/auth/naver/callback"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image, gender, age
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  access-token-expiration-minutes: 90
  refresh-token-expiration-minutes: 1000
mail:
  address:
    admin: example@admin.com
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: pharm-palm-deploy
    region:
      static: ap-northeast-2
    stack:
      auto: false